### ISSUE TITLE
Post on design patterns for financial data analysis in Python

### ISSUE THREAD

**Issue by HarmonicReflux** [ImperialCollegeLondon/RSEBlog#13]
"Design Patterns" were introduced in the seminal work by the "Gang of Four" in their 1995 book, "Design Patterns: Elements of Reusable Object-Oriented Software," originally proposed for C++. Since then, programming languages have evolved, and the concepts introduced in the book are applicable beyond just C++.

I propose to write a blog post that provides an overview of these design patterns using Python. The blog post will illustrate these concepts with a focus on applications in financial data science.

**Comment by dalonsoa** [comment]
@HarmonicReflux , do you have any tentative date for when this post will be ready? There's no urgency at all, it is simply to setup some publication schedule and try to meet it.

**Comment by HarmonicReflux** [comment]
Hello @dalonsoa,

I apologise for the delay; the blog post should have been completed earlier. I have now submitted a pull request at [PR #52](https://github.com/ImperialCollegeLondon/RSEBlog/pull/52), which addresses and closes the outdated branches (#12 and #22) related to this post.

During the writing process, I encountered issues with rendering LaTeX equations, which @dc2917 resolved (see [PR #45](https://github.com/ImperialCollegeLondon/RSEBlog/pull/45)). I also took the opportunity to rewrite parts of the post and incorporated feedback from @dc2917’s earlier review on [PR #22](https://github.com/ImperialCollegeLondon/RSEBlog/pull/22).

Feel free to provide feedback on PR #52 if you have time. I also expanded on UML more than initially planned, but I felt it deserved some attention.
