### ISSUE TITLE
 Incompatibility between arbitrary version for Python, poetry, and specified Python version in `pyproject.toml`

### ISSUE THREAD

**Issue by HarmonicReflux** [ImperialCollegeLondon/RSEBlog#23]
There is an issue with the current setup instructions for the project. The first step in the how-to guide is to ensure that Poetry is installed, see also "Make sure you have [poetry](https://python-poetry.org/docs/#installation) installed." 

However, this will not work unless Poetry is running on Python 3.11, which is the version specified in the `pyproject.toml` file.

Steps to reproduce:
- Attempt to install Poetry on a system with a Python version other than 3.11.
- Run poetry install in the project directory.
- Observe the error indicating that the current Python version is not allowed by the project.

Expected behaviour:
- Poetry should be able to install and run using the specified Python version in the `pyproject.toml`.

Actual behaviour:
- An error is thrown because the current Python version (e.g., 3.9) is not allowed by the project (^3.11).

Proposed solution:
- Update the setup instructions to ensure the user installs Python 3.11 before installing Poetry. 
This will involve:
- Clearly stating the requirement for Python 3.11 at the beginning of the guide. Maybe provide or refer to instructions to install Python 3.11 before installing Poetry.

![Screenshot from 2024-07-25 20-31-20](https://github.com/user-attachments/assets/276df664-b41b-408d-bb3b-42b714940135)

Also, on my machine, it was crucial to install the virtual environment like invoking 
`poetry install --no-root` instead of `poetry install `. Else, I am thrown this warning, which in a future version becomes an error:
```
Warning: The current project could not be installed: No file/folder found for package rseblog
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!
```

**Comment by HarmonicReflux** [comment]
The following commands solved the problem on my machine. These are equivalently the sequence of commands one might include in the project documentation.

```zsh
pyenv install 3.11  # assumes pyenv is installed (I could not survive without anymore)
pyenv local 3.11
cd ~/Downloads/vcs/RSEBlog  # navigate to your project directory; path valid for my machine
poetry config virtualenvs.in-project true  # optional to place venv in project directory
poetry install --no-root  # avoids warning "Warning: The current project could not be installed: No file/folder found for package rseblog"
```

**Comment by dalonsoa** [comment]
Lower the required python version to 3.9 to avoid any issues.
