### ISSUE TITLE
Investigate and document equations in markdown

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/RSEBlog#24]
@HarmonicReflux is having trouble rendering equations. Should figure out how to do this and make sure it's documented as part of #12.

**Comment by dc2917** [comment]
Stick this in your mkdocs.yml:

```yml
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
```

**Comment by dc2917** [comment]
@HarmonicReflux please could you test whether these work for you? If so, we can document this somewhere and then close this issue.

**Comment by HarmonicReflux** [comment]
I am sorry to keep you guys waiting on this, but I somehow can not make `mkdocs serve` run although, I modified mkdocs.yml and `pyproject.toml` as per the request:
![Screenshot from 2024-08-20 23-16-54](https://github.com/user-attachments/assets/7136f08c-568b-4e05-b98a-23b47b5e88f0)
