### ISSUE TITLE
HackMD template for collaborative blogs

### ISSUE THREAD

**Issue by SaranjeetKaur** [ImperialCollegeLondon/RSEBlog#35]
Here is a [HackMD template for writing collaborative blogs](https://hackmd.io/@SaranjeetKaur/H17O8IzcC/edit). To edit the template, please sign in with, say, GitHub.

This template is inspired from [CW24](https://www.software.ac.uk/workshop/collaborations-workshop-2024-cw24)'s speed blog template.

**Comment by dalonsoa** [comment]
Add to the README
