### ISSUE TITLE
Add admonitions and code blocks 

### ISSUE THREAD

**Issue by SaranjeetKaur** [ImperialCollegeLondon/RSEBlog#40]
Note that I've added some MkDocs extensions that I think really add to the post and allow us to do some more fun things with the blog. Namely:
- [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
- [Code Blocks](https://squidfunk.github.io/mkdocs-material/reference/code-blocks)

_Originally posted by @AdrianDAlessandro in https://github.com/ImperialCollegeLondon/RSEBlog/pull/18#pullrequestreview-2231270340_

**Comment by SaranjeetKaur** [comment]
As originally suggested by @AdrianDAlessandro, it will be nice to have instructions on how to use features like admonitions in blog posts. This can be part of the README instructions.

**Comment by AdrianDAlessandro** [comment]
The [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) theme that we use has a number of handy features. We should include links to those docs and make some specific recommendations on ones to use.

Suggestions / ones used so far:
- [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
- [Code Blocks](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/)
- There is also the images-to-figures behaviour being implemented in #36
