### ISSUE TITLE
Blog post on RSECon24

### ISSUE THREAD

**Issue by SaranjeetKaur** [ImperialCollegeLondon/RSEBlog#55]
Template that might be used: https://github.com/ImperialCollegeLondon/RSEBlog/issues/35

**Comment by AdrianDAlessandro** [comment]
Include Emily, Andy and Jeremy to contribute

**Comment by SaranjeetKaur** [comment]
Dropping Diego's suggestion here: when multiple people are contributing, convert the main issue into an umbrella issue and open sub-issues, for better tracking and management
