### ISSUE TITLE
Move/copy/port the old blog post to the new one

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/RSEBlog#7]
The old blog has a lot of stuff. We should port the most recent posts (maybe since Adrian's post on Python on MacOS) to the new infrastructure.

**Comment by AdrianDAlessandro** [comment]
Let me know when you get to including my blogpost on M1 Macs because I originally wrote it in markdown, so I have a version of it available with the appropriate formatting, etc.

**Comment by SaranjeetKaur** [comment]
> Let me know when you get to including my blogpost on M1 Macs because I originally wrote it in markdown, so I have a version of it available with the appropriate formatting, etc.

Ok that would be very helpful! There is a work-in-progress PR and it does not have proper format for the code blocks, etc.. I will drop you a message when I get to it, unless Sahil wants to pick it up.
